// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VenomVerseApi.Models;

#nullable disable

namespace VenomVerseApi.Migrations
{
    [DbContext(typeof(VenomVerseContext))]
    [Migration("20230802144722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScannedImageSerpent", b =>
                {
                    b.Property<long>("ActualSerpentSerpentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScannedImageActualResultScannedImageId")
                        .HasColumnType("bigint");

                    b.HasKey("ActualSerpentSerpentId", "ScannedImageActualResultScannedImageId");

                    b.HasIndex("ScannedImageActualResultScannedImageId");

                    b.ToTable("ScannedImageSerpent");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Catcher", b =>
                {
                    b.Property<long>("CatcherId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ApprovedDateOne")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ApprovedDateThree")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ApprovedDateTwo")
                        .HasColumnType("date");

                    b.Property<bool>("ApprovedFlag")
                        .HasColumnType("boolean");

                    b.Property<long?>("ApprovedPersonIdOne")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApprovedPersonIdThree")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApprovedPersonIdTwo")
                        .HasColumnType("bigint");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<string[]>("CatcherEvidence")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[,]>("CatcherRating")
                        .HasColumnType("text[]");

                    b.Property<float?>("ChargingFee")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("text");

                    b.HasKey("CatcherId");

                    b.ToTable("Catcher");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityAdmin", b =>
                {
                    b.Property<long>("CommunityAdminId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunityBookId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("JoinedDate")
                        .HasColumnType("date");

                    b.HasKey("CommunityAdminId");

                    b.HasIndex("CommunityBookId");

                    b.ToTable("CommunityAdmin");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityArticle", b =>
                {
                    b.Property<long>("CommunityArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("CommunityArticleId"));

                    b.Property<long?>("ApprovedUserId")
                        .HasColumnType("bigint");

                    b.Property<string[]>("ArticleCopyright")
                        .HasColumnType("text[]");

                    b.Property<string[,]>("ArticleReport")
                        .HasColumnType("text[]");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[,]>("Comment")
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string[]>("Media")
                        .HasColumnType("text[]");

                    b.Property<long[]>("React")
                        .HasColumnType("bigint[]");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommunityArticleId");

                    b.HasIndex("ApprovedUserId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CommunityArticle");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityBook", b =>
                {
                    b.Property<long>("CommunityBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("CommunityBookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<string[]>("BookCopyright")
                        .HasColumnType("text[]");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Media")
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<long>("SavedBook")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("UploadedDate")
                        .HasColumnType("date");

                    b.Property<long>("UploadedUserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommunityBookId");

                    b.HasIndex("SavedBook");

                    b.HasIndex("UploadedUserId")
                        .IsUnique();

                    b.ToTable("CommunityBook");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityPost", b =>
                {
                    b.Property<long>("CommunityPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("CommunityPostId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[,]>("Comment")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Media")
                        .HasColumnType("text[]");

                    b.Property<string[,]>("PostReport")
                        .HasColumnType("text[]");

                    b.Property<long[]>("React")
                        .HasColumnType("bigint[]");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("CommunityPostId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CommunityPost");
                });

            modelBuilder.Entity("VenomVerseApi.Models.EmergencyContact", b =>
                {
                    b.Property<long>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("EmergencyContactId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencySpecialNote")
                        .HasColumnType("text");

                    b.Property<string>("HospitalName")
                        .HasColumnType("text");

                    b.Property<string>("PerssonName")
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.HasKey("EmergencyContactId");

                    b.ToTable("EmergencyContact");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("QuestionId"));

                    b.Property<string[,]>("AnswerList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("ApprovedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Marks")
                        .HasColumnType("real");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<string[]>("QuestionMedia")
                        .HasColumnType("text[]");

                    b.Property<string>("QuestionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WriterId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex("ApprovedUserId")
                        .IsUnique();

                    b.ToTable("Question");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Quiz", b =>
                {
                    b.Property<long>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("QuizId"));

                    b.Property<float?>("AttemptedMarks")
                        .HasColumnType("real");

                    b.Property<float?>("PassMark")
                        .HasColumnType("real");

                    b.Property<string>("QuizType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("TotalMarks")
                        .HasColumnType("real");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("QuizId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("VenomVerseApi.Models.RegistrationRequest", b =>
                {
                    b.Property<long>("RegistrationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RegistrationRequestId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegistrationRequestId");

                    b.ToTable("RegistrationRequest");
                });

            modelBuilder.Entity("VenomVerseApi.Models.RequestService", b =>
                {
                    b.Property<long>("RequestServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RequestServiceId"));

                    b.Property<bool>("AcceptFlag")
                        .HasColumnType("boolean");

                    b.Property<long?>("CatcherId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<bool>("CompleteFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FakeReqFlag")
                        .HasColumnType("boolean");

                    b.Property<long>("ReqUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ScannedImageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SelectedSerpent")
                        .HasColumnType("bigint");

                    b.Property<string[]>("ServiceFeedback")
                        .HasColumnType("text[]");

                    b.Property<float?>("ServiceRating")
                        .HasColumnType("real");

                    b.HasKey("RequestServiceId");

                    b.HasIndex("CatcherId")
                        .IsUnique();

                    b.HasIndex("ReqUserId")
                        .IsUnique();

                    b.HasIndex("SelectedSerpent")
                        .IsUnique();

                    b.ToTable("RequestService");
                });

            modelBuilder.Entity("VenomVerseApi.Models.ScannedImage", b =>
                {
                    b.Property<long>("ScannedImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("ScannedImageId"));

                    b.Property<float?>("Accuracy")
                        .HasColumnType("real");

                    b.Property<long[]>("ActualSerpentType")
                        .HasColumnType("bigint[]");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherSerpentType")
                        .HasColumnType("text");

                    b.Property<long?>("PredictedSerpentType")
                        .HasColumnType("bigint");

                    b.Property<bool?>("PredictionSuccess")
                        .HasColumnType("boolean");

                    b.Property<string[,]>("PredictionVerification")
                        .HasColumnType("text[]");

                    b.Property<string>("ScannedImageMedia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ScannedImgId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScannedImageId");

                    b.HasIndex("PredictedSerpentType");

                    b.HasIndex("ScannedImgId");

                    b.HasIndex("UploadedUserId")
                        .IsUnique();

                    b.ToTable("ScannedImage");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Serpent", b =>
                {
                    b.Property<long>("SerpentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("SerpentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[,]>("SerpentMedia")
                        .HasColumnType("text[]");

                    b.Property<string[,]>("SerpentSafetyInstruction")
                        .HasColumnType("text[]");

                    b.Property<string>("SinhalaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("text");

                    b.Property<string>("SubFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Venomous")
                        .HasColumnType("real");

                    b.HasKey("SerpentId");

                    b.ToTable("Serpent");
                });

            modelBuilder.Entity("VenomVerseApi.Models.SystemAdmin", b =>
                {
                    b.Property<long>("SystemAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("SystemAdminId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemAdminId");

                    b.ToTable("SystemAdmin");
                });

            modelBuilder.Entity("VenomVerseApi.Models.SystemReport", b =>
                {
                    b.Property<long>("SystemReportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GeneratedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemReportId");

                    b.ToTable("SystemReport");
                });

            modelBuilder.Entity("VenomVerseApi.Models.UserDetail", b =>
                {
                    b.Property<long>("UserDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("UserDetailId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CatcherPrevilege")
                        .HasColumnType("boolean");

                    b.Property<bool>("CommunityAdminPrevilege")
                        .HasColumnType("boolean");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("CurrentMarks")
                        .HasColumnType("real");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<bool>("ExpertPrevilege")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long[]>("PurchasedBook")
                        .HasColumnType("bigint[]");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long[]>("SavedArticle")
                        .HasColumnType("bigint[]");

                    b.Property<long[]>("SavedBook")
                        .HasColumnType("bigint[]");

                    b.Property<long[]>("SavedPost")
                        .HasColumnType("bigint[]");

                    b.Property<long[]>("SavedResearch")
                        .HasColumnType("bigint[]");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ZoologistPrevilege")
                        .HasColumnType("boolean");

                    b.HasKey("UserDetailId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserDetail");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Zoologist", b =>
                {
                    b.Property<long>("ZoologistId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<long?>("ApprovedPersonId")
                        .HasColumnType("bigint");

                    b.Property<string[,]>("Certification")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("text");

                    b.HasKey("ZoologistId");

                    b.ToTable("Zoologist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScannedImageSerpent", b =>
                {
                    b.HasOne("VenomVerseApi.Models.Serpent", null)
                        .WithMany()
                        .HasForeignKey("ActualSerpentSerpentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.ScannedImage", null)
                        .WithMany()
                        .HasForeignKey("ScannedImageActualResultScannedImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenomVerseApi.Models.Catcher", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("Catcher")
                        .HasForeignKey("VenomVerseApi.Models.Catcher", "CatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityAdmin", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("CommunityAdmin")
                        .HasForeignKey("VenomVerseApi.Models.CommunityAdmin", "CommunityAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.CommunityBook", "CommunityBook")
                        .WithMany()
                        .HasForeignKey("CommunityBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityArticle", b =>
                {
                    b.HasOne("VenomVerseApi.Models.CommunityAdmin", "CommunityAdmin")
                        .WithOne("CommunityArticle")
                        .HasForeignKey("VenomVerseApi.Models.CommunityArticle", "ApprovedUserId");

                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("CommunityArticle")
                        .HasForeignKey("VenomVerseApi.Models.CommunityArticle", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityBook", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithMany("CommunityBook")
                        .HasForeignKey("SavedBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.Zoologist", "Zoologist")
                        .WithOne("CommunityBook")
                        .HasForeignKey("VenomVerseApi.Models.CommunityBook", "UploadedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zoologist");
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityPost", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("CommunityPost")
                        .HasForeignKey("VenomVerseApi.Models.CommunityPost", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Notification", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("Notification")
                        .HasForeignKey("VenomVerseApi.Models.Notification", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Question", b =>
                {
                    b.HasOne("VenomVerseApi.Models.Zoologist", "Zoologist")
                        .WithOne("Question")
                        .HasForeignKey("VenomVerseApi.Models.Question", "ApprovedUserId");

                    b.Navigation("Zoologist");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Quiz", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("Quiz")
                        .HasForeignKey("VenomVerseApi.Models.Quiz", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.RequestService", b =>
                {
                    b.HasOne("VenomVerseApi.Models.Catcher", "Catcher")
                        .WithOne("RequestService")
                        .HasForeignKey("VenomVerseApi.Models.RequestService", "CatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("RequestService")
                        .HasForeignKey("VenomVerseApi.Models.RequestService", "ReqUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.Serpent", "Serpent")
                        .WithOne("RequestService")
                        .HasForeignKey("VenomVerseApi.Models.RequestService", "SelectedSerpent");

                    b.Navigation("Catcher");

                    b.Navigation("Serpent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.ScannedImage", b =>
                {
                    b.HasOne("VenomVerseApi.Models.Serpent", "PredictedSerpent")
                        .WithMany("ScannedImagePredictedResult")
                        .HasForeignKey("PredictedSerpentType");

                    b.HasOne("VenomVerseApi.Models.RequestService", "RequestService")
                        .WithMany("ScannedImg")
                        .HasForeignKey("ScannedImgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("ScannedImage")
                        .HasForeignKey("VenomVerseApi.Models.ScannedImage", "UploadedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredictedSerpent");

                    b.Navigation("RequestService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.SystemReport", b =>
                {
                    b.HasOne("VenomVerseApi.Models.SystemAdmin", "SystemAdmin")
                        .WithOne("SystemReport")
                        .HasForeignKey("VenomVerseApi.Models.SystemReport", "SystemReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemAdmin");
                });

            modelBuilder.Entity("VenomVerseApi.Models.UserDetail", b =>
                {
                    b.HasOne("VenomVerseApi.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Zoologist", b =>
                {
                    b.HasOne("VenomVerseApi.Models.UserDetail", "User")
                        .WithOne("Zoologist")
                        .HasForeignKey("VenomVerseApi.Models.Zoologist", "ZoologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Catcher", b =>
                {
                    b.Navigation("RequestService")
                        .IsRequired();
                });

            modelBuilder.Entity("VenomVerseApi.Models.CommunityAdmin", b =>
                {
                    b.Navigation("CommunityArticle")
                        .IsRequired();
                });

            modelBuilder.Entity("VenomVerseApi.Models.RequestService", b =>
                {
                    b.Navigation("ScannedImg");
                });

            modelBuilder.Entity("VenomVerseApi.Models.Serpent", b =>
                {
                    b.Navigation("RequestService")
                        .IsRequired();

                    b.Navigation("ScannedImagePredictedResult");
                });

            modelBuilder.Entity("VenomVerseApi.Models.SystemAdmin", b =>
                {
                    b.Navigation("SystemReport")
                        .IsRequired();
                });

            modelBuilder.Entity("VenomVerseApi.Models.UserDetail", b =>
                {
                    b.Navigation("Catcher")
                        .IsRequired();

                    b.Navigation("CommunityAdmin")
                        .IsRequired();

                    b.Navigation("CommunityArticle")
                        .IsRequired();

                    b.Navigation("CommunityBook");

                    b.Navigation("CommunityPost")
                        .IsRequired();

                    b.Navigation("Notification")
                        .IsRequired();

                    b.Navigation("Quiz")
                        .IsRequired();

                    b.Navigation("RequestService")
                        .IsRequired();

                    b.Navigation("ScannedImage")
                        .IsRequired();

                    b.Navigation("Zoologist")
                        .IsRequired();
                });

            modelBuilder.Entity("VenomVerseApi.Models.Zoologist", b =>
                {
                    b.Navigation("CommunityBook");

                    b.Navigation("Question")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
